---

- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "os/{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "os/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os/{{ ansible_distribution }}.yml"
    - "os/{{ ansible_os_family }}.yml"
  tags:
    - always

- name: Include keycloak-specific variables
  include_vars: "keycloak/{{ keycloak_version }}.yml"
  tags:
    - always


### Install Java with OS-specific packages
- include: "java/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  tags:
    - always

- name: Capture logged in user name
  set_fact:
    loggedin_user: "{{ansible_user_id}}"


#### Extract keycloak from archive

- name: Create keycloak directory
  file:
    path: "/tmp/keycloak-tmp"
    state: directory
  tags: "download_extract"

- name: Download keycloak archive file
  get_url:
    url: "{{keycloak_archive_url}}"
    dest: "/tmp/keycloak_archive"
  tags: "download_extract"

- name: unpack keycloak
  unarchive:
    src: "/tmp/keycloak_archive"
    dest: "/tmp/keycloak-tmp"
    copy: no
  tags: "download_extract"

- name: Find keycloak extracted folder name
  find:
    paths: /tmp/keycloak-tmp
    patterns: 'keycloak*'
    file_type: directory
    recurse: no
  register: find_result
  tags: "download_extract"

- name: Move extracted keycloak to final keycloak folder
  command: "mv {{find_result.files[0].path}} {{keycloak_home}}"
  tags: "download_extract"

######## Create postgresql plugin

- name: create postresql plugin dir with parent directories
  file:
    path: "{{keycloak_home}}/modules/system/layers/keycloak/org/postgresql/main"
    state: directory
  tags: "postgresql_plugin"

- name: Download postgresql JDBC driver
  get_url:
    url: "https://jdbc.postgresql.org/download/{{postgresql_jar_name}}"
    dest: "{{keycloak_home}}/modules/system/layers/keycloak/org/postgresql/main"
  tags: "postgresql_plugin"
    
- name: Installing postgresql plugin 
  template:
    src: templates/module.xml.j2
    dest: "{{keycloak_home}}/modules/system/layers/keycloak/org/postgresql/main/module.xml"
  tags: "postgresql_plugin"

######## Install template standalone-ha.xml  

- name: install keycloak configuration
  template:
    mode: 0644
    src: templates/{{keycloak_version}}/standalone-ha.xml.j2
    dest: "{{keycloak_home}}/standalone/configuration/standalone-ha.xml"
  tags: "copy_config"

############### Setup admin user

- name: Remove file (delete file)
  ansible.builtin.file:
    path: "{{keycloak_home}}/standalone/configuration/keycloak-add-user.json"
    state: absent
  tags: "setup_admin"

- name: create admin user
  shell: "{{keycloak_home}}/bin/add-user-keycloak.sh -u {{ keycloak_admin_username }} -p {{ keycloak_admin_password }}"
  args:
    executable: /bin/bash
  tags: "setup_admin"

############### Setup keycloak as a service

- name: keycloak systemd setup
  template:
    owner: root
    group: root
    mode: 0644
    src: templates/keycloak.service.j2
    dest: /etc/systemd/system/keycloak.service
  become: yes
  tags: "setup_sys_service"

- name: enable keycloak
  systemd:
    name: keycloak
    enabled: yes
  become: yes
  tags: "setup_sys_service"

- name: start/restart keycloak
  systemd:
    name: keycloak
    state: restarted
  become: yes
  tags: "setup_sys_service"

### install other plugins

- name: Install other plugins
  import_tasks: "install_plugins.yml"
  tags: "plugins"
  notify:
    - Restart keycloak


##### configure keycloak

- name: Configure various keycloak aspects
  import_tasks: "configure_keycloak.yml"
  tags: "configure"
  notify:
    - Restart keycloak