---
# rsync is required from this role to run properly
- name: Ensure RSYNC is installed
  apt:
    name: rsync
    state: present
    install_recommends: no
  become: yes

- name: Ensure COmanage Registry root directory exists
  file:
    path: "{{ comanage_root_dir }}"
    state: directory
    owner: root
    group: root
  become: yes

# update: if no, do not retrieve new revisions from the origin repository
- name: Ensure COmanage Registry source is cloned under root directory
  git:
    repo: "{{ comanage_repo }}"
    dest: "{{ comanage_root_dir }}/comanage-registry-{{ comanage_version }}"
    version: "{{ comanage_version }}"
    accept_hostkey: yes
    update: no
  register: GCOmanageCheck
  become: yes

- name: Git pull COmanage Registry changes
  shell: /usr/bin/git pull origin
  args:
    executable: /bin/bash
    warn: false
    chdir: "{{ comanage_root_dir }}/comanage-registry-{{ comanage_version }}"
  register: GCOmanagePull
  become: yes

- debug:
    var: GCOmanagePull.stdout
    verbosity: 1

- name: Ensure symbolic link to current COmanage Registry installation exists
  file:
    src: "{{ comanage_root_dir }}/comanage-registry-{{ comanage_version }}"
    dest: "{{ comanage_path }}"
    state: link
    owner: root
    group: root
  become: yes
  when: GCOmanageCheck.changed

- name: Ensure COmanage Registry webroot directory exists
  file:
    src: "{{ comanage_path }}/app/webroot"
    dest: "{{ comanage_webroot }}"
    state: link
    owner: root
    group: root
  become: yes
  when: GCOmanageCheck.changed

# Print check output
- name: Debug msg inventory_hostname
  debug:
    msg: "{{ inventory_hostname }}"
    verbosity: 1

- name: Configure /var/cache/registry directory
  synchronize:
    src: "{{ comanage_path }}/app/tmp.dist/"
    dest: "{{ comanage_temp_dir }}"
    recursive: yes
    rsync_opts:
      - "--chmod=Du=rwx,Fu=rwx"
      - "--chown=www-data:www-data"
  become: yes
  delegate_to: "{{ inventory_hostname }}"

- name: Ensure link to COmanage Registry temp directory exists
  file:
    src: "{{ comanage_temp_dir }}"
    dest: "{{ comanage_path }}/local/tmp"
    state: link
    owner: root
    group: root
  become: yes
  when: GCOmanageCheck.changed
...