---


ssp_mods_extra_enabled: []
ssp_modules_db: []


# Examples of use cases:

## Modules
#ssp_mods_extra_disabled:
#  - name: module-a
#    module_path: "{{ ssp_path }}/modules/module_directory_name"
#  - name: module-x
#    module_path: "{{ ssp_path }}/modules/module-x"
#    dest_config_path: "{{ ssp_path }}/config/module_x.php"
#  - name: module-x
#    module_path: "{{ ssp_path }}/modules/module-x-v2.1.1"
#    dest_config_path: "{{ ssp_path }}/config/module_x.php"
#
#
#ssp_mods_extra_enabled:
#  - name: "module1"
#    path: "{{ ssp_path }}/modules/module1_directory"
#    repo_url: "https://github.com/example/module1.git"
#    version: "release-3.0"
#    # Specify ( if you have a template for this module ) the path for the template file.
#    src_config_path: "{{ role_path }}/templates/config/module1_config.php.j2"
#    dest_config_path: "{{ ssp_path }}/config/module1_config.php"
#  - name: "module2"
#    path: "{{ ssp_path }}/modules/module2_directory"
#    repo_url: "https://github.com/example/module2.git"
#    version: "devel"
#    # config_path: It does not have - so I just do not set this value.
#  - name: "module3"
#    path: "{{ ssp_path }}/modules/module3_directory"
#    repo_url: "https://github.com/example/module3.git"
#    version: "master"
#  # Themes (from repository)
#  - name: "theme1"
#    path: "{{ ssp_path }}/modules/theme1"
#    repo_url: "https://github.com/example/theme1.git"
#    version: "release-2.0.0"
#    src_config_path: "{{ role_path }}/templates/config/module_theme1_config.php.j2"
#    dest_config_path: "{{ ssp_path }}/config/module_theme1_config.php"
#  # Themes (from release zip)
#  - name: "theme2"
#    fullname: "simplesamlphp-module-theme2 - 1st level of unziped directory"
#    path: "{{ ssp_path }}/modules/themeX"
#    zip_url: "https://github.com/example/simplesamlphp-module-theme2/releases/download/2.0.0/theme2.zip"
#    version: "2.0.0"
#    src_config_path: "{{ role_path }}/templates/config/module_theme2_config.php.j2"
#    # or for example :
#    src_config_path: "{{ inventory_dir }}/files/templates/config/module_theme2_config.php.j2"
#    dest_config_path: "{{ ssp_path }}/config/module_theme2_config.php"
#  - name: "theme3"
#    fullname: "simplesamlphp-module-theme3 - 1st level of unziped directory"
#    path: "{{ ssp_path }}/modules/theme3"
#    zip_url: "https://github.com/example/simplesamlphp-module-theme3/releases/download/1.0.0/theme3.zip"
#    version: "1.0.0"
#    src_config_path: "{{ role_path }}/templates/config/module_theme3_config.php.j2"
#    src_config_path: "{{ inventory_dir }}/files/templates/config/module_theme3_config.php.j2"
#    dest_config_path: "{{ ssp_path }}/config/module_theme3_config.php"
#    Same module/theme but in a different directory ( different version )
#  - name: "theme3"
#    fullname: "simplesamlphp-module-theme3 - 1st level of unziped directory"
#    path: "{{ ssp_path }}/modules/theme3-v2.1.1"  # The different directory!
#    zip_url: "https://github.com/example/simplesamlphp-module-theme3/releases/download/2.1.1/theme3.zip"
#    version: "2.1.1"
#    src_config_path: "{{ role_path }}/templates/config/module_theme3_config.php.j2"
#    src_config_path: "{{ inventory_dir }}/files/templates/config/module_theme3_config.php.j2"
#    dest_config_path: "{{ ssp_path }}/config/module_theme3_config.php"
#
#
## Extra dictionaries
#ssp_mods_extra_dictionaries:
#  - name: module_dictionary_1
#    src_path: "{{ inventory_dir }}/files/templates/dictionaries/tabs.definition.json.j2"
#    dest_path: "{{ ssp_path }}/modules/discopower/dictionaries/tabs.definition.json"
#  - name: module_dictionary_2
#    src_path: "{{ inventory_dir }}/files/templates/dictionaries/theme/default.definition.json"
#    dest_path: "{{ ssp_path }}/modules/theme/dictionaries/default.definition.json"
#
#
## Database
#ssp_modules_db:
#  - db_host: "127.0.0.1" or "{{ lookup('dig', groups['dbmaster'][0]) }}"
#    db_name: database_name or "{{ rciam_dbs.proxy.name }}"
#    db_username: database_username or "{{ rciam_dbs.proxy.owner_username }}"
#    db_password: database_password or "{{ rciam_dbs.proxy.owner_password }}"
#    db_script_path: "{{ ssp_path }}/modules/amodule/configfiles/pgsql_tables.sql"

